# Generated by Django 5.2.3 on 2025-07-07 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcast_name', models.CharField(max_length=100)),
                ('driver_number', models.IntegerField(unique=True)),
                ('first_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=50)),
                ('meeting_key', models.IntegerField()),
                ('team_colour', models.CharField(blank=True, max_length=7, null=True)),
                ('team_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=4)),
                ('headshot_url', models.URLField(blank=True, null=True)),
                ('name_acronym', models.CharField(blank=True, max_length=3, null=True)),
                ('session_key', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='car_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver_number', models.IntegerField()),
                ('session_key', models.IntegerField()),
                ('date', models.DateTimeField()),
                ('speed', models.IntegerField()),
                ('throttle', models.IntegerField()),
                ('brake', models.IntegerField()),
                ('n_gear', models.IntegerField()),
                ('meeting_key', models.IntegerField()),
            ],
            options={
                'unique_together': {('driver_number', 'session_key', 'date')},
            },
        ),
    ]
