# Generated by Django 5.2.3 on 2025-08-04 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sessions',
            fields=[
                ('circuit_key', models.IntegerField()),
                ('circuit_short_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=4)),
                ('country_key', models.IntegerField()),
                ('country_name', models.CharField(max_length=100)),
                ('date_end', models.DateTimeField()),
                ('date_start', models.DateTimeField()),
                ('gmt_offset', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=100)),
                ('meeting_key', models.IntegerField()),
                ('session_key', models.IntegerField(primary_key=True, serialize=False)),
                ('session_name', models.CharField(max_length=100)),
                ('session_type', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
            ],
            options={
                'verbose_name': 'Session',
            },
        ),
        migrations.CreateModel(
            name='driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('broadcast_name', models.CharField(max_length=100)),
                ('driver_number', models.IntegerField()),
                ('first_name', models.CharField(max_length=50)),
                ('full_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=50)),
                ('team_colour', models.CharField(blank=True, max_length=7, null=True)),
                ('team_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=4)),
                ('headshot_url', models.URLField(blank=True, null=True)),
                ('name_acronym', models.CharField(blank=True, max_length=3, null=True)),
                ('sessions', models.ManyToManyField(to='f1_races.sessions')),
            ],
        ),
        migrations.CreateModel(
            name='car_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField()),
                ('speed', models.IntegerField()),
                ('throttle', models.IntegerField()),
                ('brake', models.IntegerField()),
                ('n_gear', models.IntegerField()),
                ('meeting_key', models.IntegerField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1_races.driver')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='f1_races.sessions')),
            ],
            options={
                'unique_together': {('driver', 'session', 'date')},
            },
        ),
    ]
