# Generated by Django 5.2.3 on 2025-07-08 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_races', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_number',
            field=models.IntegerField(),
        ),
    ]
