# Generated by Django 5.2.6 on 2025-09-17 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_races', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructors',
            name='bestChampionshipPosition',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constructors',
            name='bestRaceResult',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constructors',
            name='bestStartingGridPosition',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constructors',
            name='total1And2Finishes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constructors',
            name='totalChampionshipWins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constructors',
            name='totalPodiumRaces',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constructors',
            name='totalPodiums',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constructors',
            name='totalRaceEntries',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constructors',
            name='totalRaceLaps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constructors',
            name='totalRaceStarts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constructors',
            name='totalRaceWins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
