# Generated by Django 5.2.6 on 2025-09-17 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_races', '0002_alter_constructors_bestchampionshipposition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructors',
            name='totalChampionshipPoints',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constructors',
            name='totalFastestLaps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constructors',
            name='totalPoints',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constructors',
            name='totalPolePositions',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
