# Generated by Django 5.2.3 on 2025-07-08 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f1_races', '0002_alter_driver_driver_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='driver',
            unique_together=set(),
        ),
    ]
