# Generated by Django 5.2.3 on 2025-07-08 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_races', '0003_alter_driver_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='sessions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('circuit_key', models.IntegerField()),
                ('circuit_short_name', models.CharField(max_length=100)),
                ('country_code', models.CharField(max_length=4)),
                ('country_key', models.IntegerField()),
                ('country_name', models.CharField(max_length=100)),
                ('date_end', models.DateTimeField()),
                ('date_start', models.DateTimeField()),
                ('gmt_offset', models.IntegerField()),
                ('location', models.CharField(max_length=100)),
                ('meeting_key', models.IntegerField()),
                ('session_key', models.IntegerField()),
                ('session_name', models.CharField(max_length=100)),
                ('session_type', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
            ],
        ),
    ]
