# Generated by Django 5.2.6 on 2025-09-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_races', '0003_alter_constructors_totalchampionshippoints_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='countries',
            name='demonym',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
