# Generated by Django 5.2.6 on 2025-09-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_races', '0004_alter_countries_demonym'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enginesmanufacturers',
            name='bestChampionshipPosition',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enginesmanufacturers',
            name='bestRaceResult',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enginesmanufacturers',
            name='bestStartingGridPosition',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enginesmanufacturers',
            name='fullName',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='enginesmanufacturers',
            name='total1And2Finishes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enginesmanufacturers',
            name='totalChampionshipPoints',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enginesmanufacturers',
            name='totalChampionshipWins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enginesmanufacturers',
            name='totalFastestLaps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enginesmanufacturers',
            name='totalPodiumRaces',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enginesmanufacturers',
            name='totalPodiums',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enginesmanufacturers',
            name='totalPoints',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enginesmanufacturers',
            name='totalPolePositions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enginesmanufacturers',
            name='totalRaceEntries',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enginesmanufacturers',
            name='totalRaceLaps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enginesmanufacturers',
            name='totalRaceStarts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='enginesmanufacturers',
            name='totalRaceWins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
