# Generated by Django 5.2.3 on 2025-07-08 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_races', '0004_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions',
            name='gmt_offset',
            field=models.CharField(max_length=10),
        ),
    ]
