# Generated by Django 5.2.6 on 2025-09-17 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_races', '0005_alter_enginesmanufacturers_bestchampionshipposition_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='engines',
            name='capacity',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
