# Generated by Django 5.2.6 on 2025-09-17 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_races', '0006_alter_engines_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grandprix',
            name='countriesID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grand_prix_countriesID', to='f1_races.countries'),
        ),
    ]
