# Generated by Django 5.2.6 on 2025-09-17 00:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_races', '0007_alter_grandprix_countriesid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drivers',
            name='abbreviation',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='bestChampionshipPosition',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='bestRaceResult',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='bestStartingGridPosition',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='countryOfBirthID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers_country_of_birth', to='f1_races.countries'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='dateOfBirth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='firstName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='fullName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='gender',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='lastName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='nationalityCountryID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='drivers_nationality', to='f1_races.countries'),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='permanentNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='placeOfBirth',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='totalChampionshipPoints',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='totalChampionshipWins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='totalDriverOfTheDay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='totalFastestLaps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='totalGrandSlams',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='totalPodiums',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='totalPoints',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='totalPolePositions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='totalRaceEntries',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='totalRaceLaps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='totalRaceStarts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drivers',
            name='totalRaceWins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
