# Generated by Django 5.2.6 on 2025-09-17 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_races', '0008_alter_drivers_abbreviation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tyremanufacturers',
            name='bestRaceResult',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tyremanufacturers',
            name='bestStartingGridPosition',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tyremanufacturers',
            name='countriesID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tyre_manufacturers_countriesID', to='f1_races.countries'),
        ),
        migrations.AlterField(
            model_name='tyremanufacturers',
            name='totalFastestLaps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tyremanufacturers',
            name='totalPodiumRaces',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tyremanufacturers',
            name='totalPodiums',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tyremanufacturers',
            name='totalPolePositions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tyremanufacturers',
            name='totalRaceEntries',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tyremanufacturers',
            name='totalRaceLaps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tyremanufacturers',
            name='totalRaceStarts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='tyremanufacturers',
            name='totalRaceWins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
