# Generated by Django 5.2.6 on 2025-09-17 00:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_races', '0009_alter_tyremanufacturers_bestraceresult_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='races',
            name='constructorsChampionshipDecider',
        ),
        migrations.RemoveField(
            model_name='races',
            name='driversChampionshipDecider',
        ),
        migrations.AlterField(
            model_name='races',
            name='circuitsID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_circuitsID', to='f1_races.circuits'),
        ),
        migrations.AlterField(
            model_name='races',
            name='courseLength',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='direction',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='races',
            name='distance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='grandPrixID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_grandPrixID', to='f1_races.grandprix'),
        ),
        migrations.AlterField(
            model_name='races',
            name='laps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='officialName',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='races',
            name='qualifyingFormat',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='races',
            name='round',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='scheduledDistance',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='scheduledLaps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='sprintQualifyingFormat',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='races',
            name='time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='turns',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_year', to='f1_races.sessions'),
        ),
    ]
