# Generated by Django 5.2.6 on 2025-09-17 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_races', '0010_remove_races_constructorschampionshipdecider_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='races',
            name='constructorsChampionshipDecider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='races',
            name='driversChampionshipDecider',
            field=models.BooleanField(default=False),
        ),
    ]
