# Generated by Django 5.2.4 on 2025-09-17 23:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_races', '0011_races_constructorschampionshipdecider_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='constructors_chronology',
            name='parentConstructorID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentConstructorID', to='f1_races.constructors'),
        ),
        migrations.AlterField(
            model_name='constructors_chronology',
            name='positionDisplayOrder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constructors_chronology',
            name='yearFrom',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='constructors_chronology',
            name='yearTo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drivers_family_relations',
            name='parentDriverID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parentDriverID', to='f1_races.drivers'),
        ),
        migrations.AlterField(
            model_name='drivers_family_relations',
            name='positionDisplayOrder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='drivers_family_relations',
            name='type',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='races_constructors',
            name='constructorID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_constructors_constructorID', to='f1_races.constructors'),
        ),
        migrations.AlterField(
            model_name='races_constructors',
            name='engineManufacturerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_constructors_engineManufacturerID', to='f1_races.enginesmanufacturers'),
        ),
        migrations.AlterField(
            model_name='races_constructors',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_constructors',
            name='positionsGained',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_constructors_standings',
            name='constructorID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_constructors_standings_constructorID', to='f1_races.constructors'),
        ),
        migrations.AlterField(
            model_name='races_constructors_standings',
            name='engineManufacturerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_constructors_standings_engineManufacturerID', to='f1_races.enginesmanufacturers'),
        ),
        migrations.AlterField(
            model_name='races_constructors_standings',
            name='points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_constructors_standings',
            name='positionsGained',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_driver_of_the_day_results',
            name='constructorID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_driver_of_the_day_results_constructorID', to='f1_races.constructors'),
        ),
        migrations.AlterField(
            model_name='races_driver_of_the_day_results',
            name='engineManufacturerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_driver_of_the_day_results_engineManufacturerID', to='f1_races.enginesmanufacturers'),
        ),
        migrations.AlterField(
            model_name='races_driver_of_the_day_results',
            name='points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_driver_of_the_day_results',
            name='positionsGained',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_driver_standings',
            name='driverID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_driver_standings_driverID', to='f1_races.drivers'),
        ),
        migrations.AlterField(
            model_name='races_driver_standings',
            name='points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_driver_standings',
            name='positionsGained',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_fastest_laps',
            name='constructorsID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_fastest_laps_constructorsID', to='f1_races.constructors'),
        ),
        migrations.AlterField(
            model_name='races_fastest_laps',
            name='driverID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_fastest_laps_driverID', to='f1_races.drivers'),
        ),
        migrations.AlterField(
            model_name='races_fastest_laps',
            name='driverNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_fastest_laps',
            name='engineManufacturerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_fastest_laps_engineManufacturerID', to='f1_races.enginesmanufacturers'),
        ),
        migrations.AlterField(
            model_name='races_fastest_laps',
            name='lap',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_fastest_laps',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_fastest_laps',
            name='timeMillis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_fastest_laps',
            name='tyreManufacturersID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_fastest_laps_tyresManufacturerID', to='f1_races.tyremanufacturers'),
        ),
        migrations.AlterField(
            model_name='races_free_practice1_results',
            name='constructorsID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_free_practice1_results_constructorsID', to='f1_races.constructors'),
        ),
        migrations.AlterField(
            model_name='races_free_practice1_results',
            name='driverID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_free_practice1_results_driverID', to='f1_races.drivers'),
        ),
        migrations.AlterField(
            model_name='races_free_practice1_results',
            name='driverNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_free_practice1_results',
            name='engineManufacturerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_free_practice1_results_engineManufacturerID', to='f1_races.enginesmanufacturers'),
        ),
        migrations.AlterField(
            model_name='races_free_practice1_results',
            name='laps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_free_practice1_results',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_free_practice1_results',
            name='timeMillis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_free_practice1_results',
            name='tyreManufacturersID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_free_practice1_results_tyresManufacturerID', to='f1_races.tyremanufacturers'),
        ),
        migrations.AlterField(
            model_name='races_free_practice2_results',
            name='constructorsID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_free_practice2_results_constructorsID', to='f1_races.constructors'),
        ),
        migrations.AlterField(
            model_name='races_free_practice2_results',
            name='driverID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_free_practice2_results_driverID', to='f1_races.drivers'),
        ),
        migrations.AlterField(
            model_name='races_free_practice2_results',
            name='driverNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_free_practice2_results',
            name='engineManufacturerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_free_practice2_results_engineManufacturerID', to='f1_races.enginesmanufacturers'),
        ),
        migrations.AlterField(
            model_name='races_free_practice2_results',
            name='laps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_free_practice2_results',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_free_practice2_results',
            name='timeMillis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_free_practice2_results',
            name='tyreManufacturersID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_free_practice2_results_tyresManufacturerID', to='f1_races.tyremanufacturers'),
        ),
        migrations.AlterField(
            model_name='races_free_practice3_results',
            name='constructorsID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_free_practice3_results_constructorsID', to='f1_races.constructors'),
        ),
        migrations.AlterField(
            model_name='races_free_practice3_results',
            name='driverID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_free_practice3_results_driverID', to='f1_races.drivers'),
        ),
        migrations.AlterField(
            model_name='races_free_practice3_results',
            name='driverNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_free_practice3_results',
            name='engineManufacturerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_free_practice3_results_engineManufacturerID', to='f1_races.enginesmanufacturers'),
        ),
        migrations.AlterField(
            model_name='races_free_practice3_results',
            name='laps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_free_practice3_results',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_free_practice3_results',
            name='timeMillis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_free_practice3_results',
            name='tyreManufacturersID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_free_practice3_results_tyresManufacturerID', to='f1_races.tyremanufacturers'),
        ),
        migrations.AlterField(
            model_name='races_free_practice4_results',
            name='constructorsID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_free_practice4_results_constructorsID', to='f1_races.constructors'),
        ),
        migrations.AlterField(
            model_name='races_free_practice4_results',
            name='driverID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_free_practice4_results_driverID', to='f1_races.drivers'),
        ),
        migrations.AlterField(
            model_name='races_free_practice4_results',
            name='driverNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_free_practice4_results',
            name='engineManufacturerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_free_practice4_results_engineManufacturerID', to='f1_races.enginesmanufacturers'),
        ),
        migrations.AlterField(
            model_name='races_free_practice4_results',
            name='laps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_free_practice4_results',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_free_practice4_results',
            name='timeMillis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_free_practice4_results',
            name='tyreManufacturersID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_free_practice4_results_tyresManufacturerID', to='f1_races.tyremanufacturers'),
        ),
        migrations.AlterField(
            model_name='races_pit_stops',
            name='constructorsID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_pit_stops_constructorsID', to='f1_races.constructors'),
        ),
        migrations.AlterField(
            model_name='races_pit_stops',
            name='driverID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_pit_stops_driverID', to='f1_races.drivers'),
        ),
        migrations.AlterField(
            model_name='races_pit_stops',
            name='driverNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_pit_stops',
            name='engineManufacturerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_pit_stops_engineManufacturerID', to='f1_races.enginesmanufacturers'),
        ),
        migrations.AlterField(
            model_name='races_pit_stops',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_pit_stops',
            name='timeMillis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_pit_stops',
            name='tyreManufacturersID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_pit_stops_tyresManufacturerID', to='f1_races.tyremanufacturers'),
        ),
        migrations.AlterField(
            model_name='races_pre_qualifying_results',
            name='constructorsID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_pre_qualifying_results_constructorsID', to='f1_races.constructors'),
        ),
        migrations.AlterField(
            model_name='races_pre_qualifying_results',
            name='driverID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_pre_qualifying_results_driverID', to='f1_races.drivers'),
        ),
        migrations.AlterField(
            model_name='races_pre_qualifying_results',
            name='driverNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_pre_qualifying_results',
            name='engineManufacturerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_pre_qualifying_results_engineManufacturerID', to='f1_races.enginesmanufacturers'),
        ),
        migrations.AlterField(
            model_name='races_pre_qualifying_results',
            name='laps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_pre_qualifying_results',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_pre_qualifying_results',
            name='timeMillis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_pre_qualifying_results',
            name='tyreManufacturersID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_pre_qualifying_results_tyresManufacturerID', to='f1_races.tyremanufacturers'),
        ),
        migrations.AlterField(
            model_name='races_qualifying1_results',
            name='constructorsID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_qualifying1_results_constructorsID', to='f1_races.constructors'),
        ),
        migrations.AlterField(
            model_name='races_qualifying1_results',
            name='driverID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_qualifying1_results_driverID', to='f1_races.drivers'),
        ),
        migrations.AlterField(
            model_name='races_qualifying1_results',
            name='driverNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_qualifying1_results',
            name='engineManufacturerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_qualifying1_results_engineManufacturerID', to='f1_races.enginesmanufacturers'),
        ),
        migrations.AlterField(
            model_name='races_qualifying1_results',
            name='laps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_qualifying1_results',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_qualifying1_results',
            name='timeMillis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_qualifying1_results',
            name='tyreManufacturersID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_qualifying1_results_tyresManufacturerID', to='f1_races.tyremanufacturers'),
        ),
        migrations.AlterField(
            model_name='races_qualifying2_results',
            name='constructorsID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_qualifying2_results_constructorsID', to='f1_races.constructors'),
        ),
        migrations.AlterField(
            model_name='races_qualifying2_results',
            name='driverID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_qualifying2_results_driverID', to='f1_races.drivers'),
        ),
        migrations.AlterField(
            model_name='races_qualifying2_results',
            name='driverNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_qualifying2_results',
            name='engineManufacturerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_qualifying2_results_engineManufacturerID', to='f1_races.enginesmanufacturers'),
        ),
        migrations.AlterField(
            model_name='races_qualifying2_results',
            name='laps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_qualifying2_results',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_qualifying2_results',
            name='timeMillis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_qualifying2_results',
            name='tyreManufacturersID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_qualifying2_results_tyresManufacturerID', to='f1_races.tyremanufacturers'),
        ),
        migrations.AlterField(
            model_name='races_qualifying_results',
            name='constructorsID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_qualifying_results_constructorsID', to='f1_races.constructors'),
        ),
        migrations.AlterField(
            model_name='races_qualifying_results',
            name='driverID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_qualifying_results_driverID', to='f1_races.drivers'),
        ),
        migrations.AlterField(
            model_name='races_qualifying_results',
            name='driverNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_qualifying_results',
            name='engineManufacturerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_qualifying_results_engineManufacturerID', to='f1_races.enginesmanufacturers'),
        ),
        migrations.AlterField(
            model_name='races_qualifying_results',
            name='laps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_qualifying_results',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_qualifying_results',
            name='timeMillis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_qualifying_results',
            name='tyreManufacturersID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_qualifying_results_tyresManufacturerID', to='f1_races.tyremanufacturers'),
        ),
        migrations.AlterField(
            model_name='races_race_results',
            name='constructorsID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_race_results_constructorsID', to='f1_races.constructors'),
        ),
        migrations.AlterField(
            model_name='races_race_results',
            name='driverID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_race_results_driverID', to='f1_races.drivers'),
        ),
        migrations.AlterField(
            model_name='races_race_results',
            name='driverNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_race_results',
            name='engineManufacturerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_race_results_engineManufacturerID', to='f1_races.enginesmanufacturers'),
        ),
        migrations.AlterField(
            model_name='races_race_results',
            name='laps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_race_results',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_race_results',
            name='timeMillis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_race_results',
            name='tyreManufacturersID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_race_results_tyresManufacturerID', to='f1_races.tyremanufacturers'),
        ),
        migrations.AlterField(
            model_name='races_sprint_qualifying',
            name='constructorsID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_sprint_qualifying_constructorsID', to='f1_races.constructors'),
        ),
        migrations.AlterField(
            model_name='races_sprint_qualifying',
            name='driverID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_sprint_qualifying_driverID', to='f1_races.drivers'),
        ),
        migrations.AlterField(
            model_name='races_sprint_qualifying',
            name='driverNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_sprint_qualifying',
            name='engineManufacturerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_sprint_qualifying_engineManufacturerID', to='f1_races.enginesmanufacturers'),
        ),
        migrations.AlterField(
            model_name='races_sprint_qualifying',
            name='laps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_sprint_qualifying',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_sprint_qualifying',
            name='timeMillis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_sprint_qualifying',
            name='tyreManufacturersID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_sprint_qualifying_tyresManufacturerID', to='f1_races.tyremanufacturers'),
        ),
        migrations.AlterField(
            model_name='races_sprint_race_results',
            name='constructorsID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_sprint_race_results_constructorsID', to='f1_races.constructors'),
        ),
        migrations.AlterField(
            model_name='races_sprint_race_results',
            name='driverID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_sprint_race_results_driverID', to='f1_races.drivers'),
        ),
        migrations.AlterField(
            model_name='races_sprint_race_results',
            name='driverNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_sprint_race_results',
            name='engineManufacturerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_sprint_race_results_engineManufacturerID', to='f1_races.enginesmanufacturers'),
        ),
        migrations.AlterField(
            model_name='races_sprint_race_results',
            name='laps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_sprint_race_results',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_sprint_race_results',
            name='timeMillis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_sprint_race_results',
            name='tyreManufacturersID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_sprint_race_results_tyresManufacturerID', to='f1_races.tyremanufacturers'),
        ),
        migrations.AlterField(
            model_name='races_sprint_starting_grid_positions',
            name='constructorsID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_sprint_starting_grid_positions_constructorsID', to='f1_races.constructors'),
        ),
        migrations.AlterField(
            model_name='races_sprint_starting_grid_positions',
            name='driverID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_sprint_starting_grid_positions_driverID', to='f1_races.drivers'),
        ),
        migrations.AlterField(
            model_name='races_sprint_starting_grid_positions',
            name='driverNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_sprint_starting_grid_positions',
            name='engineManufacturerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_sprint_starting_grid_positions_engineManufacturerID', to='f1_races.enginesmanufacturers'),
        ),
        migrations.AlterField(
            model_name='races_sprint_starting_grid_positions',
            name='gridPenalty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_sprint_starting_grid_positions',
            name='gridPenaltyPositions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_sprint_starting_grid_positions',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_sprint_starting_grid_positions',
            name='timeMillis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_sprint_starting_grid_positions',
            name='tyreManufacturersID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_sprint_starting_grid_positions_tyresManufacturerID', to='f1_races.tyremanufacturers'),
        ),
        migrations.AlterField(
            model_name='races_starting_grid_positions',
            name='constructorsID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_starting_grid_positions_constructorsID', to='f1_races.constructors'),
        ),
        migrations.AlterField(
            model_name='races_starting_grid_positions',
            name='driverID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_starting_grid_positions_driverID', to='f1_races.drivers'),
        ),
        migrations.AlterField(
            model_name='races_starting_grid_positions',
            name='driverNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_starting_grid_positions',
            name='engineManufacturerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_starting_grid_positions_engineManufacturerID', to='f1_races.enginesmanufacturers'),
        ),
        migrations.AlterField(
            model_name='races_starting_grid_positions',
            name='gridPenalty',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_starting_grid_positions',
            name='gridPenaltyPositions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_starting_grid_positions',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_starting_grid_positions',
            name='timeMillis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_starting_grid_positions',
            name='tyreManufacturersID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_starting_grid_positions_tyresManufacturerID', to='f1_races.tyremanufacturers'),
        ),
        migrations.AlterField(
            model_name='races_warming_up_results',
            name='constructorsID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_warming_up_results_constructorsID', to='f1_races.constructors'),
        ),
        migrations.AlterField(
            model_name='races_warming_up_results',
            name='driverID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_warming_up_results_driverID', to='f1_races.drivers'),
        ),
        migrations.AlterField(
            model_name='races_warming_up_results',
            name='driverNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_warming_up_results',
            name='engineManufacturerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_warming_up_results_engineManufacturerID', to='f1_races.enginesmanufacturers'),
        ),
        migrations.AlterField(
            model_name='races_warming_up_results',
            name='laps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_warming_up_results',
            name='time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_warming_up_results',
            name='timeMillis',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_warming_up_results',
            name='tyreManufacturersID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_warming_up_results_tyresManufacturerID', to='f1_races.tyremanufacturers'),
        ),
        migrations.AlterField(
            model_name='sessions_constructors',
            name='bestRaceResult',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_constructors',
            name='bestStartingGridPosition',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_constructors',
            name='positionNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_constructors',
            name='positionText',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sessions_constructors',
            name='total1And2Finishes',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_constructors',
            name='totalFastestLaps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_constructors',
            name='totalPodiumRaces',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_constructors',
            name='totalPodiums',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_constructors',
            name='totalPoints',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_constructors',
            name='totalPolePositions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_constructors',
            name='totalRaceEntries',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_constructors',
            name='totalRaceWins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_constructors',
            name='totalRacesLaps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_constructors_standings',
            name='enginesManufacturerID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions_constructors_standings_enginesManufacturerID', to='f1_races.enginesmanufacturers'),
        ),
        migrations.AlterField(
            model_name='sessions_constructors_standings',
            name='points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_constructors_standings',
            name='positionDisplayOrder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_constructors_standings',
            name='positionNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_constructors_standings',
            name='positionText',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sessions_drivers',
            name='bestRaceResult',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_drivers',
            name='bestStartingGridPosition',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_drivers',
            name='positionNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_drivers',
            name='positionText',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sessions_drivers',
            name='totalDriverOfTheDay',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_drivers',
            name='totalFastestLaps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_drivers',
            name='totalGrandSlams',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_drivers',
            name='totalPodiums',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_drivers',
            name='totalPoints',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_drivers',
            name='totalPolePositions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_drivers',
            name='totalRaceEntries',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_drivers',
            name='totalRaceLaps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_drivers',
            name='totalRaceStarts',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_drivers',
            name='totalRaceWins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_drivers_standings',
            name='points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_drivers_standings',
            name='positionDisplayOrder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_drivers_standings',
            name='positionNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_drivers_standings',
            name='positionText',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sessions_engines_manufacturers',
            name='bestRaceResult',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_engines_manufacturers',
            name='bestStartingGridPosition',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_engines_manufacturers',
            name='positionNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_engines_manufacturers',
            name='positionText',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sessions_engines_manufacturers',
            name='totalFastestLaps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_engines_manufacturers',
            name='totalPodiumRaces',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_engines_manufacturers',
            name='totalPodiums',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_engines_manufacturers',
            name='totalPoints',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_engines_manufacturers',
            name='totalPolePositions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_engines_manufacturers',
            name='totalRaceEntries',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_engines_manufacturers',
            name='totalRaceLaps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_engines_manufacturers',
            name='totalRaceWins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_entrants_drivers',
            name='rounds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_entrants_drivers',
            name='roundsText',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='sessions_tyre_manufacturers',
            name='bestRaceResult',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_tyre_manufacturers',
            name='bestStartingGridPosition',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_tyre_manufacturers',
            name='totalFastestLaps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_tyre_manufacturers',
            name='totalPodiumRaces',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_tyre_manufacturers',
            name='totalPodiums',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_tyre_manufacturers',
            name='totalPolePositions',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_tyre_manufacturers',
            name='totalRaceEntries',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_tyre_manufacturers',
            name='totalRaceLaps',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_tyre_manufacturers',
            name='totalRaceWins',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sessions_tyre_manufacturers',
            name='totalRacesStarts',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
