# Generated by Django 5.2.4 on 2025-09-17 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_races', '0012_alter_constructors_chronology_parentconstructorid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='races_constructors',
            name='points',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_constructors',
            name='positionsGained',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
