# Generated by Django 5.2.4 on 2025-09-17 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_races', '0013_alter_races_constructors_points_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='races_constructors',
            name='positionDisplayOrder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_constructors',
            name='positionNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_constructors',
            name='round',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
