# Generated by Django 5.2.4 on 2025-09-17 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_races', '0015_rename_points_races_driver_of_the_day_results_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='races_driver_standings',
            name='positionDisplayOrder',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_driver_standings',
            name='positionNumber',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_driver_standings',
            name='raceID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='races_driver_standings', to='f1_races.races'),
        ),
        migrations.AlterField(
            model_name='races_driver_standings',
            name='round',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='races_driver_standings',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='year_races_driver_standings', to='f1_races.sessions'),
        ),
    ]
