# Generated by Django 5.2.6 on 2025-09-17 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_races', '0020_alter_races_sprint_starting_grid_positions_gridpenalty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='races_starting_grid_positions',
            name='gridPenalty',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
