# Generated by Django 5.2.6 on 2025-09-17 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_races', '0021_alter_races_starting_grid_positions_gridpenalty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sessions_entrants_drivers',
            name='rounds',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
