# Generated by Django 5.2.6 on 2025-09-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1_races', '0023_alter_races_racesid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='races',
            name='racesID',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
